#!/bin/bash

# Script responsável por criar um lançador de aplicativo para uma aplicação qualquer no menu do sistema
# Autor: Emanuel Moraes
# Email: emanuelmoraes297@gmail.com

Name="$1"
Exec="$2"
Icon="$3"
Categories="$4"

function adapter {
	rt="$1"

	if ! which "$rt" 1> /dev/null 2> /dev/null && ([[ "$rt" != /* ]] || ! [ -f "$rt" ]); then
	    rt="${rt// /\\ }"
		if [ "$(pwd)" = "/" ]; then
			rt="/$rt"
		else
			rt="$(pwd)/$rt"
		fi
	fi

	if ! which "$rt" 1> /dev/null 2> /dev/null && ([[ "$rt" != /* ]] || ! [ -f "$rt" ]); then
		rt="$1"
	fi

	echo $rt
}

if [ -z "$Name" ];then
	echo "Erro: Informe o nome do aplicativo"
	exit 101
fi

if [ -z "$Exec" ]; then
	echo "Erro: Informe o path do aplicativo"
	exit 102
fi

Exec=$(adapter "$Exec")
Icon=$(adapter "$Icon")

if [ "$(id -u)" = "0" ]; then
	echo "\
[Desktop Entry]
Encoding=UTF-8
Type=Application
Terminal=false
Name=$Name
Exec=$Exec
Icon=$Icon
Categories=$Categories\
" > "/usr/share/applications/$Name.desktop"
else
	echo "\
[Desktop Entry]
Encoding=UTF-8
Type=Application
Terminal=false
Name=$Name
Exec=$Exec
Icon=$Icon
Categories=$Categories\
" > "$HOME/.local/share/applications/$Name.desktop"
fi
